language: php
php:
  - 7.2
  - 7.3
  - 7.4

  # omitting "script:" will default to phpunit
notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  include:
    - stage: Test
      install:
        - composer install
      script:
        - vendor/bin/phpunit
