language: php

cache:
  directories:
    - $HOME/.composer/cache
php:

  - '7.3'
  - '7.4'

  # omitting "script:" will default to phpunit
notifications:
  email:
    on_success: never
    on_failure: change


before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit
